<?php
$conf = array(
		"background"=>"http://app.tvie.com.cn/static/images/background.png",
		"splash"=>"http://app.tvie.com.cn/static/images/background.png",
		"api"=>array(
				"related"=>"http://app.tvie.com.cn/api/v1/movie/recent/query/",
				"detail"=>"http://app.tvie.com.cn/api/v1/movie/detail/query/",
				"views"=>"http://app.tvie.com.cn/api/v1/statistic/view/"
			),
		"modules"=>array(
			array(
				"id"=>"serial",
				"position"=>"0,0,0.2286,1",
				"app"=>"com.tvie.ibox.live.mianyang",
				"param"=>array(
						"query_channels_api"=>"http://api.vdnplus.com/api/public/mcms/getLivelist"
					),
				"title"=>"直播",
				"icon"=>"",
				"pic"=>"http://app.tvie.com.cn/static/images/serial.jpg",
				"api"=>"http://app.tvie.com.cn/api/v1/serial/query/",
				"filter"=>""
			),
			array(
				"id"=>"movie",
				"position"=>"0.2286,0,0.3857,0.5",
				"title"=>"电影",
				"icon"=>"",
				"pic"=>"http://app.tvie.com.cn/static/images/movie.png",
				"api"=>"http://app.tvie.com.cn/api/v1/movie/query/",
				"filter"=>""
			),
			array(
				"id"=>"zongyi",
				"position"=>"0.6143,0,0.3857,0.5",
				"title"=>"电视剧",
				"icon"=>"",
				"pic"=>"http://app.tvie.com.cn/static/images/zy.png",
				"api"=>"http://app.tvie.com.cn/api/v1/serial/query/",
				"filter"=>""
			),
			array(
				"id"=>"lanmu",
				"position"=>"0.2286,0.5,0.3,0.5",
				"title"=>"王牌栏目",
				"icon"=>"",
				"pic"=>"http://app.tvie.com.cn/static/images/wp.png",
				"api"=>"http://app.tvie.com.cn/api/v1/movie/query/",
				"filter"=>""
			),
			array(
				"id"=>"star",
				"position"=>"0.5286,0.5,0.2357,0.5",
				"title"=>"明星",
				"icon"=>"",
				"pic"=>"http://app.tvie.com.cn/static/images/star.png",
				"api"=>"http://app.tvie.com.cn/api/v1/movie/query/",
				"filter"=>""
			),
			array(
				"id"=>"hudong",
				"position"=>"0.7643,0.5,0.2357,0.5",
				"title"=>"互动",
				"icon"=>"",
				"pic"=>"http://app.tvie.com.cn/static/images/chat.png",
				"api"=>"http://app.tvie.com.cn/api/v1/movie/query/",
				"filter"=>""
			)
		)
		);
return $conf;