<?php
global $site_url;
//$site_url = "http://114.215.109.123";
$conf = array(
		//"splash"=>"$site_url/static/images/background.png",
		"splash"=>"$site_url/static/images/desktop/mianyang.png",
		"api"=>array(
			"related"=>"$site_url/api/v1/movie/query/",
			"detail"=>"$site_url/api/v1/movie/detail/query/",
			"views"=>"$site_url/api/v1/statistic/view/"
			)
		);
$conf["modules"] = array(
		// home
		array(
			"title"=>"首页",
			"tpl"=>"vod",
			"modules" => array(
				array(
				"id"=>"serial",
				"position"=>"0,0,0.2286,1",
				"app"=>"com.tvie.ibox.live.mianyang",
				"param"=>array(
						"query_channels_api"=>"$site_url/api/v1/live/channels",
						"channel_id"=>1
					),
				"title"=>"直播",
				"icon"=>"",
				"pic"=>"$site_url/static/images/serial.jpg",
				"api"=>"$site_url/api/v1/serial/query/",
				"filter"=>""
			),
			array(
				"id"=>"movie",
				"position"=>"0.2286,0,0.3857,0.5",
				"title"=>"电影",
				"icon"=>"",
				"pic"=>"$site_url/static/images/movie.png",
				"param"=>array(
					"api"=>"$site_url/api/v1/movie/query/",
					),
				"filter"=>""
			),
			array(
				"id"=>"zongyi",
				"position"=>"0.6143,0,0.3857,0.5",
				"title"=>"电视剧",
				"icon"=>"",
				"pic"=>"$site_url/static/images/zy.png",
				"param"=>array(
					"api"=>"$site_url/api/v1/serial/query/",
					),
				"filter"=>""
			),
			array(
				"id"=>"lanmu",
				"position"=>"0.2286,0.5,0.3,0.5",
				"title"=>"王牌栏目",
				"icon"=>"",
				"pic"=>"$site_url/static/images/wp.png",
				"param"=>array(
						"api"=>"$site_url/api/v1/movie/query/",
					),
				"filter"=>""
			),
			array(
				"id"=>"star",
				"position"=>"0.5286,0.5,0.2357,0.5",
				"title"=>"明星",
				"icon"=>"",
				"pic"=>"$site_url/static/images/star.png",
				"param"=>array(
						"api"=>"$site_url/api/v1/movie/query/",
					),
				"filter"=>""
			),
			array(
				"id"=>"hudong",
				"position"=>"0.7643,0.5,0.2357,0.5",
				"title"=>"互动",
				"icon"=>"",
				"pic"=>"$site_url/static/images/chat.png",
				"param"=>array(
						"api"=>"$site_url/api/v1/movie/query/",
					),
				"filter"=>""
			)
		)
		),
		//资讯
		array(
			"title"=>"资讯",
			"tpl"=>"vod",
			"modules"=>array(
				array(
					"tpl"=>"cate",
					"id"=>"wenhuayishu",
					"position"=>"0.0,0.2,0.3,0.6",
					"title"=>"新闻",
					"icon"=>"",
					"pic"=>"$site_url/static/images/wp.png",
					"background"=>"$site_url/static/images/desktop/sky.jpg",
					"param"=>array(
						"api"=>"$site_url/api/v1/movie/query/"
					),
					"categories"=>array(
							array(
									//"position"=>"0.0,0.2,0.3,0.6",
									"title"=>"分类1",
									"icon"=>"",
									"pic"=>"$site_url/static/images/wp.png",
									"param"=>array(
										"api"=>"$site_url/api/v1/movie/query/"
									),
								),
							array(
									//"position"=>"0.35,0.2,0.3,0.6",
									"title"=>"分类2",
									"icon"=>"",
									"pic"=>"$site_url/static/images/wp.png",
									"param"=>array(
										"api"=>"$site_url/api/v1/movie/query/"
									),

								)
						)
				),
				array(
					"id"=>"wenhuayishu",
					"position"=>"0.35,0.2,0.3,0.6",
					"title"=>"新闻",
					"icon"=>"",
					"pic"=>"$site_url/static/images/wp.png",
					"param"=>array(
						"api"=>"$site_url/api/v1/movie/query/"
					)
				),
			)
		),
		// live
		array(
			"title"=>"电视",
			"tpl"=>"live",
			"app"=>"com.tvie.ibox.live.mianyang",
			"param"=>array(
					//"preview"=>1,
					"api"=>"$site_url/api/v1/live/channels",
					"query_channels_api"=>"$site_url/api/v1/live/channels",
					"channel_id"=>1,
					"lines"=>4,
					"num_of_line"=>4
				)
		),
		//资讯
		array(
			"title"=>"专题",
			"tpl"=>"vod",
			"modules"=>array(
				array(
					"id"=>"special1",
					"position"=>"0.1,0.1,0.35,0.6",
					"title"=>"专题1",
					"tpl"=>"special",
					"icon"=>"",
					"pic"=>"$site_url/static/images/chat.png",
					"background"=>"$site_url/static/images/desktop/sky.jpg",
					"param"=>array(
						"api"=>"$site_url/api/v1/movie/query/",
					),
					"filter"=>""
				),
				array(
					"id"=>"special2",
					"position"=>"0.6,0.1,0.35,0.6",
					"title"=>"专题2",
					"tpl"=>"special",
					"icon"=>"",
					"pic"=>"$site_url/static/images/chat.png",
					"param"=>array(
						"api"=>"$site_url/api/v1/movie/query/",
						"background"=>"$site_url/static/images/desktop/couple.jpg"
					),
					"filter"=>""
				),
			)
		),
	);
return $conf;